common: &common
    adapter: postgresql
    username: postgres
    password: password
    host: localhost
    port: 5432
    
development:
    <<: *common
    database: sb_development


test:
    <<: *common
    database: sb_test

production:
    <<: *common
    database: sb_production
